title:              Waleed Ahmad
email:              waleed.bin.zafar@gmail.com
description:        Data Professional and Consultant
author:             Waleed Ahmad
baseurl:            ""
url:                "http://waleedbinzafar.github.io"

# Social Profiles
twitter_username:   glwr666
github_username:    waleedbinzafar
facebook_username:  glwr666
linkedin_username:  waleedbinzafar

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
